translations = {
    "en": {
        "welcome_message": "Welcome to DEDSEC-PROTECT-KIT",
        "scan_url": "Scan an URL",
        "scan_apk": "Scan an APK",
        "scan_file": "Scan a File",
        "info": "INFO",
        "change_language": "Change language",
        "exit": "Exit",
        "update_script": "Update the script",
        "choose_option": "Choose an option: ",
        "enter_link": "Enter the link to check: ",
        "enter_apk_path": "Enter the APK path to check: ",
        "enter_file_path": "Enter the file path to check: ",
        "enter_language": "Enter the language (en/fr/ht): ",
        "goodbye_message": "Goodbye!",
        "invalid_option": "Invalid option, please try again.",
        "developed_by": "Developed by: FAMOUS-TECH | ʜᴀᴄᴋᴇʀ₁₆₀₉",
        "contact": "Contact: +1 (409) 995-3525 whattsapp only",
        "thanks_for_using": "THANKS FOR USING THIS SCRIPT",
        "send_malicious_links": "send me all malicious link you know pls i need to create a big database. bye!",
        "malicious_link_detected": "Malicious link detected!",
        "safe_link": "Safe link.",
        "link_not_found": "Link not found in VirusTotal database.",
        "error_connecting": "Error connecting to VirusTotal.",
        "suspicious_domain_detected": "Suspicious domain detected! Similar to {}",
        "known_malicious_link": "Malicious link detected! (Known malicious link)",
        "malicious_apk_detected": "Malicious APK detected!",
        "safe_apk": "Safe APK.",
        "apk_not_found": "APK not found in VirusTotal database.",
        "malicious_file_detected": "Malicious file detected!",
        "safe_file": "Safe file.",
        "file_not_found": "File not found in VirusTotal database."
    },
    "fr": {
        "welcome_message": "Bienvenue dans DEDSEC-PROTECT-KIT",
        "scan_url": "Scanner une URL",
        "scan_apk": "Scanner un APK",
        "scan_file": "Scanner un Fichier",
        "info": "INFO",
        "change_language": "Changer la langue",
        "exit": "Quitter",
        "update_script": "Mettre à jour le script",
        "choose_option": "Choisissez une option: ",
        "enter_link": "Entrez le lien à vérifier: ",
        "enter_apk_path": "Entrez le chemin de l'APK à vérifier: ",
        "enter_file_path": "Entrez le chemin du fichier à vérifier: ",
        "enter_language": "Entrez la langue (en/fr/ht): ",
        "goodbye_message": "Au revoir!",
        "invalid_option": "Option invalide, veuillez réessayer.",
        "developed_by": "Développé par: FAMOUS-TECH | ʜᴀᴄᴋᴇʀ₁₆₀₉",
        "contact": "Contact: +1 (409) 995-3525 whattsapp only",
        "thanks_for_using": "MERCI D'UTILISER CE SCRIPT",
        "send_malicious_links": "envoyez-moi tous les liens malveillants que vous connaissez s'il vous plaît, j'ai besoin de créer une grande base de données. au revoir!",
        "malicious_link_detected": "Lien malveillant détecté!",
        "safe_link": "Lien sûr.",
        "link_not_found": "Lien non trouvé dans la base de données VirusTotal.",
        "error_connecting": "Erreur de connexion à VirusTotal.",
        "suspicious_domain_detected": "Domaine suspect détecté! Similaire à {}",
        "known_malicious_link": "Lien malveillant détecté! (Lien malveillant connu)",
        "malicious_apk_detected": "APK malveillant détecté!",
        "safe_apk": "APK sûr.",
        "apk_not_found": "APK non trouvé dans la base de données VirusTotal.",
        "malicious_file_detected": "Fichier malveillant détecté!",
        "safe_file": "Fichier sûr.",
        "file_not_found": "Fichier non trouvé dans la base de données VirusTotal."
    },
    "ht": {
        "welcome_message": "Byenveni nan DEDSEC-PROTECT-KIT",
        "scan_url": "Tcheke yon URL",
        "scan_apk": "Tcheke yon APK",
        "scan_file": "Tcheke yon Fichye",
        "info": "INFO",
        "change_language": "Chanje lang",
        "exit": "Sòti",
        "update_script": "Mete ajou script la",
        "choose_option": "Chwazi yon opsyon: ",
        "enter_link": "Antre lyen la pou tcheke: ",
        "enter_apk_path": "Antre chemen APK la pou tcheke: ",
        "enter_file_path": "Antre chemen fichye a pou tcheke: ",
        "enter_language": "Antre lang (en/fr/ht): ",
        "goodbye_message": "Adye!",
        "invalid_option": "Opsyon invalid, tanpri eseye ankò.",
        "developed_by": "Devlope pa: FAMOUS-TECH | ʜᴀᴄᴋᴇʀ₁₆₀₉",
        "contact": "Kontak: +1 (409) 995-3525 whattsapp only",
        "thanks_for_using": "MIE GRATITUDE POU ITILIZE SCRIPT SA",
        "send_malicious_links": "voye m' tout lyen malizyè ou konnen tanpri mwen bezwen kreye yon gwo baz done. bye!",
        "malicious_link_detected": "Lyen malizyè detekte!",
        "safe_link": "Lyen sekir.",
        "link_not_found": "Lyen pa jwenn nan baz done VirusTotal.",
        "error_connecting": "Erè konekte ak VirusTotal.",
        "suspicious_domain_detected": "Domèn sispèk detekte! Menm jan ak {}",
        "known_malicious_link": "Lyen malveyan detekte! (Lyen malizyè konnen)",
        "malicious_apk_detected": "APK malizyè detekte!",
        "safe_apk": "APK sekirize.",
        "apk_not_found": "APK pa jwenn nan baz done VirusTotal la gen kèk chans pou li danje.",
        "malicious_file_detected": "Fichye malizyè detekte!",
        "safe_file": "Fichye sekirize.",
        "file_not_found": "Fichye pa jwenn nan baz done VirusTotal."
    }
}

current_language = "en"

def set_language(lang):
    global current_language
    if lang in translations:
        current_language = lang

def get_translation(key):
    return translations[current_language].get(key, "Translation not found")
